/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.qt.view.component.imp;

import com.qt.view.component.UpdateValuePanel;
import java.awt.Color;

/**
 *
 * @author Admin
 */
public class CarStatusPanal extends UpdateValuePanel {

    /**
     * Creates new form CarStatusPanal
     */
    public CarStatusPanal() {
        initComponents();
        setOpaque(false);
        setBackground(new Color(240, 240, 240, 86));
        this.stValue.setValue("0");
        this.stNt.setBlink(true);
        this.stNp.setBlink(true);
        this.stPt.setBlink(true);
    }

    @Override
    protected void updateValues() {
        this.stAt.setStatus(this.carModel.isAt());
        this.stNt.setStatus(this.carModel.isNt());
        this.stNp.setStatus(this.carModel.isNp());
        this.stPt.setStatus(this.carModel.isPt());
        this.stCm.setStatus(this.carModel.isCm());
        this.stAt.setStatus(this.carModel.isAt());
        this.stS1.setStatus(this.carModel.isS1());
        this.stS2.setStatus(this.carModel.isS2());
        this.stS3.setStatus(this.carModel.isS3());
        int n = this.carModel.getGearBoxValue();
        this.stValue.setValue(String.format("%s", n == 0 ? "N" : n));
        int st = this.carModel.getStatus();
        if (st == 0) {
            this.stValue.setIconName("Dừng");
        } else if (st > 0) {
            this.stValue.setIconName("Tiến");
        } else if (st < 0) {
            this.stValue.setIconName("Lùi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stAt = new com.qt.view.element.StatusPanel();
        stPt = new com.qt.view.element.StatusPanel();
        stNt = new com.qt.view.element.StatusPanel();
        stNp = new com.qt.view.element.StatusPanel();
        stValue = new com.qt.view.element.StatusPanel();
        stCm = new com.qt.view.element.StatusPanel();
        stS2 = new com.qt.view.element.StatusPanel();
        stS1 = new com.qt.view.element.StatusPanel();
        stS4 = new com.qt.view.element.StatusPanel();
        stS3 = new com.qt.view.element.StatusPanel();

        stAt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/AT.png"))); // NOI18N
        stAt.setIconName("Dây an toàn");

        stPt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/PT.png"))); // NOI18N
        stPt.setIconName("Phanh tay");

        stNt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/NT.png"))); // NOI18N
        stNt.setIconName("Xi nhan trái");

        stNp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/NP.png"))); // NOI18N
        stNp.setIconName("Xi nhan phải");

        stValue.setIcon(null);
        stValue.setIconName("...");

        stCm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/CM.png"))); // NOI18N
        stCm.setIconName("Chết máy");

        stS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle.png"))); // NOI18N
        stS2.setIconName("S2");

        stS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle.png"))); // NOI18N
        stS1.setIconName("S1");

        stS4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle.png"))); // NOI18N
        stS4.setIconName("S4");

        stS3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle.png"))); // NOI18N
        stS3.setIconName("S3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stPt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stNt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(stCm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stS1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stS3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stAt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stNp, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(stValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stS2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stS4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stNt, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(stNp, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stPt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stAt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stCm, javax.swing.GroupLayout.PREFERRED_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(stValue, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stS1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(stS2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stS3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(stS4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.qt.view.element.StatusPanel stAt;
    private com.qt.view.element.StatusPanel stCm;
    private com.qt.view.element.StatusPanel stNp;
    private com.qt.view.element.StatusPanel stNt;
    private com.qt.view.element.StatusPanel stPt;
    private com.qt.view.element.StatusPanel stS1;
    private com.qt.view.element.StatusPanel stS2;
    private com.qt.view.element.StatusPanel stS3;
    private com.qt.view.element.StatusPanel stS4;
    private com.qt.view.element.StatusPanel stValue;
    // End of variables declaration//GEN-END:variables

}
