/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.qt.view.component.imp;

import com.qt.view.component.UpdateValuePanel;
import java.awt.Color;

/**
 *
 * @author Admin
 */
public class CarStatusPanal extends UpdateValuePanel {

    /**
     * Creates new form CarStatusPanal
     */
    public CarStatusPanal() {
        initComponents();
        setOpaque(false);
        setBackground(new Color(240, 240, 240, 86));
        this.stValue.setValue("0");
        this.stNT.setBlink(true);
        this.stNP.setBlink(true);
        this.stPT.setBlink(true);
    }

    @Override
    protected void updateValues() {
        this.stAT.setStatus(this.carModel.isAt());
        this.stNT.setStatus(this.carModel.isNt());
        this.stNP.setStatus(this.carModel.isNp());
        this.stPT.setStatus(this.carModel.isPt());
        this.stCM.setStatus(this.carModel.isCm());
        this.stAT.setStatus(this.carModel.isAt());
        this.stT1.setStatus(this.carModel.isT1());
        this.stT2.setStatus(this.carModel.isT2());
        this.stT3.setStatus(this.carModel.isT3());
        this.stS1.setStatus(this.carModel.isS1());
        this.stS2.setStatus(this.carModel.isS2());
        this.stS3.setStatus(this.carModel.isS3());
        int n = this.carModel.getGearBoxValue();
        this.stValue.setValue(String.format("%s", n == 0 ? "N" : n));
        int st = this.carModel.getStatus();
        if (st == 0) {
            this.stValue.setIconName("Dừng");
        } else if (st > 0) {
            this.stValue.setIconName("Tiến");
        } else if (st < 0) {
            this.stValue.setIconName("Lùi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stNT = new com.qt.view.component.StatusPanel();
        stNP = new com.qt.view.component.StatusPanel();
        stAT = new com.qt.view.component.StatusPanel();
        stPT = new com.qt.view.component.StatusPanel();
        stCM = new com.qt.view.component.StatusPanel();
        stS1 = new com.qt.view.component.StatusPanel();
        stS3 = new com.qt.view.component.StatusPanel();
        stS2 = new com.qt.view.component.StatusPanel();
        stValue = new com.qt.view.component.StatusPanel();
        stT3 = new com.qt.view.component.StatusPanel();
        stT2 = new com.qt.view.component.StatusPanel();
        stT1 = new com.qt.view.component.StatusPanel();

        setH(-1);
        setRound(20);

        stNT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/NT.png"))); // NOI18N
        stNT.setIconName("NT");

        stNP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/NP.png"))); // NOI18N
        stNP.setIconName("NP");

        stAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/AT.png"))); // NOI18N
        stAT.setIconName("AT");

        stPT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/PT.png"))); // NOI18N
        stPT.setIconName("PT");

        stCM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/CM.png"))); // NOI18N
        stCM.setIconName("CM");

        stS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle.png"))); // NOI18N
        stS1.setIconName("S1");

        stS3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle.png"))); // NOI18N
        stS3.setIconName("S3");

        stS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle.png"))); // NOI18N
        stS2.setIconName("S2");

        stValue.setIconName("P");

        stT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/point.png"))); // NOI18N
        stT3.setIconName("T3");

        stT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/point.png"))); // NOI18N
        stT2.setIconName("T2");

        stT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/point.png"))); // NOI18N
        stT1.setIconName("T1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stAT, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(stNT, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(stCM, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stPT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(stNP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stS1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stS2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stS3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stT1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stT2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stT3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stNP, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(stNT, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stPT, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(stAT, javax.swing.GroupLayout.PREFERRED_SIZE, 143, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stCM, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(stValue, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stS2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(stS1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(stS3, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stT2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(stT1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(stT3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.qt.view.component.StatusPanel stAT;
    private com.qt.view.component.StatusPanel stCM;
    private com.qt.view.component.StatusPanel stNP;
    private com.qt.view.component.StatusPanel stNT;
    private com.qt.view.component.StatusPanel stPT;
    private com.qt.view.component.StatusPanel stS1;
    private com.qt.view.component.StatusPanel stS2;
    private com.qt.view.component.StatusPanel stS3;
    private com.qt.view.component.StatusPanel stT1;
    private com.qt.view.component.StatusPanel stT2;
    private com.qt.view.component.StatusPanel stT3;
    private com.qt.view.component.StatusPanel stValue;
    // End of variables declaration//GEN-END:variables

}
