/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.qt.view.component.imp;

import com.qt.common.ConstKey;
import com.qt.pretreatment.KeyEventManagement;
import com.qt.view.component.UpdateValuePanel;
import java.awt.Color;

/**
 *
 * @author Admin
 */
public class DuongTruongContestPanel extends UpdateValuePanel {


    /**
     * Creates new form DuongTruongContestPanel
     */
    public DuongTruongContestPanel() {
        initComponents();
        setOpaque(false);
        setBackground(new Color(255, 255, 255, 70));
        KeyEventManagement eventManagement = KeyEventManagement.getInstance();
        eventManagement.getEventButtonBlink().putButtonBlinkEvent(ConstKey.KEY_BOARD.ERROR.CL, btCl);
        eventManagement.getEventButtonBlink().putButtonBlinkEvent(ConstKey.KEY_BOARD.ERROR.HL, btHl);
        eventManagement.getEventButtonBlink().putButtonBlinkEvent(ConstKey.KEY_BOARD.ERROR.QT, btQt);
        eventManagement.getEventButtonBlink().putButtonBlinkEvent(ConstKey.KEY_BOARD.ERROR.RG, btRg);
        eventManagement.getEventButtonBlink().putButtonBlinkEvent(ConstKey.KEY_BOARD.ERROR.TN, btTn);
        eventManagement.getEventButtonBlink().putButtonBlinkEvent(ConstKey.KEY_BOARD.CONTEST.KT, btKt);
        eventManagement.getEventButtonBlink().putButtonBlinkEvent(ConstKey.KEY_BOARD.CONTEST.GS, btGs);
        eventManagement.getEventButtonBlink().putButtonBlinkEvent(ConstKey.KEY_BOARD.CONTEST.TS, btTs);
        eventManagement.getEventButtonBlink().putButtonBlinkEvent(ConstKey.KEY_BOARD.CONTEST.XP, btXp);
        this.btCl.setMouseClicked((design) -> {
            this.carModel.setRemoteValue(ConstKey.ERR.SWERVED_OUT_OF_LANE);
        });
        this.btHl.setMouseClicked((design) -> {
            this.carModel.setRemoteValue(ConstKey.ERR.IGNORED_INSTRUCTIONS);
        });
        this.btQt.setMouseClicked((design) -> {
            this.carModel.setRemoteValue(ConstKey.ERR.VIOLATION_TRAFFIC_RULES);
        });
        this.btRg.setMouseClicked((design) -> {
            this.carModel.setRemoteValue(ConstKey.ERR.HEAVY_SHAKING);
        });
        this.btTn.setMouseClicked((design) -> {
            this.carModel.setRemoteValue(ConstKey.ERR.CAUSED_AN_ACCIDENT);
        });
        //////////////////////////
        this.btXp.setMouseClicked((design) -> {
            this.carModel.setRemoteValue(ConstKey.KEY_BOARD.CONTEST.XP);
        });
        this.btTs.setMouseClicked((design) -> {
            this.carModel.setRemoteValue(ConstKey.KEY_BOARD.CONTEST.TS);
        });
        this.btGs.setMouseClicked((design) -> {
            this.carModel.setRemoteValue(ConstKey.KEY_BOARD.CONTEST.GS);
        });
        this.btKt.setMouseClicked((design) -> {
            this.carModel.setRemoteValue(ConstKey.KEY_BOARD.CONTEST.KT);
        });
    }

    @Override
    public void start() {
    }

    @Override
    public void stop() {
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBaiThi = new javax.swing.JPanel();
        btXp = new com.qt.view.element.ButtonDesign();
        btTs = new com.qt.view.element.ButtonDesign();
        btGs = new com.qt.view.element.ButtonDesign();
        btKt = new com.qt.view.element.ButtonDesign();
        pnTruDiem = new javax.swing.JPanel();
        btCl = new com.qt.view.element.ButtonDesign();
        btHl = new com.qt.view.element.ButtonDesign();
        btQt = new com.qt.view.element.ButtonDesign();
        btRg = new com.qt.view.element.ButtonDesign();
        btTn = new com.qt.view.element.ButtonDesign();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        setFocusCycleRoot(true);

        pnBaiThi.setOpaque(false);
        pnBaiThi.setLayout(new java.awt.GridLayout(1, 4));

        btXp.setText("Xuất phát");
        pnBaiThi.add(btXp);

        btTs.setText("Tăng tốc");
        pnBaiThi.add(btTs);

        btGs.setText("Giảm tốc");
        pnBaiThi.add(btGs);

        btKt.setText("Kết thúc");
        pnBaiThi.add(btKt);

        pnTruDiem.setOpaque(false);
        pnTruDiem.setLayout(new java.awt.GridLayout(1, 5));

        btCl.setText("CL");
        pnTruDiem.add(btCl);

        btHl.setText("HL");
        pnTruDiem.add(btHl);

        btQt.setText("QT");
        pnTruDiem.add(btQt);

        btRg.setText("RG");
        pnTruDiem.add(btRg);

        btTn.setText("TN");
        pnTruDiem.add(btTn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBaiThi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
            .addComponent(pnTruDiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnBaiThi, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnTruDiem, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.qt.view.element.ButtonDesign btCl;
    private com.qt.view.element.ButtonDesign btGs;
    private com.qt.view.element.ButtonDesign btHl;
    private com.qt.view.element.ButtonDesign btKt;
    private com.qt.view.element.ButtonDesign btQt;
    private com.qt.view.element.ButtonDesign btRg;
    private com.qt.view.element.ButtonDesign btTn;
    private com.qt.view.element.ButtonDesign btTs;
    private com.qt.view.element.ButtonDesign btXp;
    private javax.swing.JPanel pnBaiThi;
    private javax.swing.JPanel pnTruDiem;
    // End of variables declaration//GEN-END:variables
}
