/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.qt.view.component.imp;

import com.qt.view.component.UpdateValuePanel;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Admin
 */
public class InfoPanel extends UpdateValuePanel{

    /**
     * Creates new form InfoPanel
     */
    public InfoPanel() {
        super(1000);
        initComponents();
        setBackground(new Color(255, 255, 255, 70));
    }
    
    @Override
    protected void updateValues() {
        this.stCarID.setValue(this.testDataModel.getCarId());
        this.stID.setValue(this.testDataModel.getId());
        this.stModeName.setValue(this.testDataModel.getModeName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImg = new javax.swing.JLabel();
        stCarID = new com.qt.view.component.StatusPanel();
        stID = new com.qt.view.component.StatusPanel();
        stModeName = new com.qt.view.component.StatusPanel();

        setOpaque(false);
        setRound(20);

        lbImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        stCarID.setIconName("Số Xe");
        stCarID.setValue("000");

        stID.setIconName("Số Báo Danh");
        stID.setName(""); // NOI18N
        stID.setValue("000");

        stModeName.setFontValue(new java.awt.Font("Arial", 1, 30)); // NOI18N
        stModeName.setIconName("Phần Thi");
        stModeName.setName(""); // NOI18N
        stModeName.setValue("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stCarID, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addComponent(stID, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addComponent(stModeName, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbImg, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(stCarID, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stID, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stModeName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbImg;
    private com.qt.view.component.StatusPanel stCarID;
    private com.qt.view.component.StatusPanel stID;
    private com.qt.view.component.StatusPanel stModeName;
    // End of variables declaration//GEN-END:variables

    public JLabel getImageLabel() {
        return this.lbImg;
    }


}
