/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.qt.view.component.imp;

import com.qt.input.socket.YardModelHandle;
import com.qt.view.component.UpdateValuePanel;
import java.awt.Color;

/**
 *
 * @author Admin
 */
public class SenserView extends UpdateValuePanel {

    private final YardModelHandle modelHandle;
    private final Color defaultColor;

    /**
     * Creates new form SenserView
     */
    public SenserView() {
        super(200);
        initComponents();
        setOpaque(true);
        this.defaultColor = getBackground();
        this.modelHandle = YardModelHandle.getInstance();
    }

    private boolean st = false;

    @Override
    protected void updateValues() {
        boolean conn = this.modelHandle.isConnect();
        if (conn != st) {
            st = conn;
            if (conn) {
                setBackground(new Color(140, 240, 140, 86));
            } else {
                setBackground(defaultColor);
            }
        }
        this.stT1.setStatus(this.carModel.isT1());
        this.stT2.setStatus(this.carModel.isT2());
        this.stT3.setStatus(this.carModel.isT3());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stT2 = new com.qt.view.element.StatusPanel();
        stT3 = new com.qt.view.element.StatusPanel();
        stT1 = new com.qt.view.element.StatusPanel();

        stT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle.png"))); // NOI18N
        stT2.setIconName("T2");

        stT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle.png"))); // NOI18N
        stT3.setIconName("T3");

        stT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circle.png"))); // NOI18N
        stT1.setIconName("T1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stT1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stT2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stT3, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stT3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(stT2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(stT1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.qt.view.element.StatusPanel stT1;
    private com.qt.view.element.StatusPanel stT2;
    private com.qt.view.element.StatusPanel stT3;
    // End of variables declaration//GEN-END:variables
}
