/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.qt.view.component.imp;

import com.qt.contest.AbsContest;
import com.qt.view.component.UpdateValuePanel;
import java.awt.Color;

/**
 *
 * @author Admin
 */
public class ValuePanal extends UpdateValuePanel {


    /**
     * Creates new form ValuePanal
     */
    public ValuePanal() {
        initComponents();
        setOpaque(false);
        setBackground(new Color(255, 255, 255, 70));
    }

    @Override
    protected void updateValues() {
        this.stDistance.setValue(String.format("%.3f", this.carModel.getDistance()));
        this.stV.setValue(String.format("%.1f", this.carModel.getSpeed1()));
        this.stRpm.setValue(String.format("%s", this.carModel.getRpm()));
        this.stScore.setValue(String.format("%s", this.testDataModel.getScore()));
        this.stTotalTime.setValue(String.format("%d", this.testDataModel.getTestTime()/1000));
        AbsContest contest = this.testDataModel.getContest();
        if (contest != null) {
            this.stTime.setValue(String.format("%d", contest.getTestTime()/1000));
            this.stCurrContest.setValue(contest.getName());
        }else{
            this.stTime.setValue("0");
            this.stCurrContest.setValue("...");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stDistance = new com.qt.view.component.StatusPanel();
        stTime = new com.qt.view.component.StatusPanel();
        stTotalTime = new com.qt.view.component.StatusPanel();
        stRpm = new com.qt.view.component.StatusPanel();
        stV = new com.qt.view.component.StatusPanel();
        stScore = new com.qt.view.component.StatusPanel();
        stCurrContest = new com.qt.view.component.StatusPanel();

        setRound(20);

        stDistance.setIconName("Khoảng Cách (m)");
        stDistance.setRound(40);
        stDistance.setValue("0");

        stTime.setIcon(null);
        stTime.setIconName("Thời Gian (s)");
        stTime.setRound(40);
        stTime.setValue("0");

        stTotalTime.setIcon(null);
        stTotalTime.setIconName("Tổng Thời Gian (s)");
        stTotalTime.setRound(40);
        stTotalTime.setValue("0");

        stRpm.setIconName("RPM (Vòng/phút)");
        stRpm.setValue("0");

        stV.setIcon(null);
        stV.setIconName("Vận Tốc (Km/h)");
        stV.setRound(40);
        stV.setValue("0");

        stScore.setIcon(null);
        stScore.setIconName("Điểm/100");
        stScore.setRound(40);
        stScore.setValue("0");

        stCurrContest.setIconName("Bài Thi HIện Tại");
        stCurrContest.setValue("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stCurrContest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stRpm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stDistance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(stScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stV, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stTotalTime, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stRpm, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stV, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stTotalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stScore, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stTime, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stCurrContest, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.qt.view.component.StatusPanel stCurrContest;
    private com.qt.view.component.StatusPanel stDistance;
    private com.qt.view.component.StatusPanel stRpm;
    private com.qt.view.component.StatusPanel stScore;
    private com.qt.view.component.StatusPanel stTime;
    private com.qt.view.component.StatusPanel stTotalTime;
    private com.qt.view.component.StatusPanel stV;
    // End of variables declaration//GEN-END:variables

}
