/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.qt.view.frame;

import com.qt.common.ConstKey;
import com.qt.common.communication.Communicate.IgetName;
import com.qt.view.AbsKeylistenerFrame;
import com.qt.controller.settingElement.IElementSetting;
import com.qt.pretreatment.KeyEventsPackage;
import com.qt.view.interfaces.IActionCallback;

/**
 *
 * @author Admin
 * @param <T>
 */
public class MenuShowRoom<T extends IgetName> extends AbsKeylistenerFrame implements Runnable {

    private final ShowRoomBroad<T> showRoomBroad;
    private final KeyEventsPackage eventsPackage;

    /**
     * Creates new form SettingFrame
     *
     * @param clazz
     * @param okACtion
     * @param closeActon
     * @param row
     * @param col
     */
    public MenuShowRoom(Class<T> clazz,
            IActionCallback<T> okACtion,
            IActionCallback<T> closeActon,
            int row, int col) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuShowRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        initComponents();
        this.showRoomBroad = new ShowRoomBroad<>(clazz, okACtion, closeActon, row, col);
        this.pnHome.add(this.showRoomBroad);
        this.eventsPackage = this.showRoomBroad.getEventsPackage();
        this.eventsPackage.getEventButtonBlink().putButtonBlinkEvent(btCancel.getValue(), btCancel);
        btCancel.setMouseClicked((design) -> {
            close();
        });
        this.eventsPackage.putEvent(ConstKey.KEY_BOARD.CANCEL, (key) -> {
            close();
        });
    }

    public void stopTimer() {
        this.showRoomBroad.stopTimer();
    }

    public void setTimeOutAction(IActionCallback<T> timeOutAction) {
        this.showRoomBroad.setTimeOutAction(timeOutAction);
    }

    public void setTimeOut(int timeOut) {
       this.showRoomBroad.setTimeOut(timeOut);
    }

    public void setOkAction(IActionCallback<T> okAction) {
       this.showRoomBroad.setOkAction(okAction);
    }

    public void setCloseAction(IActionCallback<T> closeAction) {
        this.showRoomBroad.setCloseAction(closeAction);
    }

    public boolean removeElement(int index) {
       return this.showRoomBroad.removeElement(index);
    }

    public void removeElement(IElementSetting element) {
        this.showRoomBroad.removeElement(element);
    }

    public boolean addElement(T element) {
        return this.showRoomBroad.addElement(element);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnHome = new javax.swing.JPanel();
        btCancel = new com.qt.view.element.ButtonDesign();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnHome.setBackground(new java.awt.Color(204, 204, 204));
        pnHome.setLayout(new java.awt.GridLayout(1, 0));

        btCancel.setOnColor(new java.awt.Color(255, 102, 102));
        btCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.showRoomBroad.close();
    }//GEN-LAST:event_formWindowClosed

    public void display() {
        this.setVisible(true);
        this.showRoomBroad.display();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.qt.view.element.ButtonDesign btCancel;
    private javax.swing.JPanel pnHome;
    // End of variables declaration//GEN-END:variables

    public void close() {
        setVisible(false);
        this.showRoomBroad.close();
    }
    
    @Override
    public void run() {
        display();
    }

    public void removeAllElement() {
        this.showRoomBroad.removeAllElement();
    }
}
