/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.qt.view.component;

import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class ShowMessagePanel extends javax.swing.JPanel {

    private static volatile ShowMessagePanel instance;
    private Timer timer;

    /**
     * Creates new form ShowMessagePanel
     */
    private ShowMessagePanel() {
        initComponents();
        timer = new Timer(10000, (e) -> {
            lbMess.setText(null);
            timer.stop();
        });
    }

    public void showMess(String mess) {
        if (mess != null) {
            this.timer.start();
        }
        lbMess.setText(mess);
    }

    public static ShowMessagePanel getInstance() {
        ShowMessagePanel ins = instance;
        if (ins == null) {
            synchronized (ShowMessagePanel.class) {
                ins = instance;
                if (ins == null) {
                    ins = instance = new ShowMessagePanel();
                }
            }
        }
        return ins;
    }

    public JLabel getLbMess() {
        return lbMess;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMess = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());
        add(lbMess, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbMess;
    // End of variables declaration//GEN-END:variables
}
