/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.qt.view;

import com.qt.model.input.CarModel;
import com.qt.model.modelTest.process.TestDataModelView;
import javax.swing.JLabel;


/**
 *
 * @author Admin
 */
public class PanelHome extends DesignPanel {

    /**
     * Creates new form PanelHome
     */
    public PanelHome() {
        initComponents();
//        setOpaque(false);
    }

    public void setCarModel(CarModel carModel) {
        this.pnCarStatus.setCarModel(carModel);
        this.pnValue.setCarModel(carModel);
        this.pnInfo.setCarModel(carModel);
    }
    
    public void setTestDataModel(TestDataModelView testDataModel) {
        this.pnCarStatus.setTestDataModel(testDataModel);
        this.pnValue.setTestDataModel(testDataModel);
        this.pnInfo.setTestDataModel(testDataModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCarStatus = new com.qt.view.component.imp.CarStatusPanal();
        pnInfo = new com.qt.view.component.imp.InfoPanel();
        pnValue = new com.qt.view.component.imp.ValuePanal();

        setColor(new java.awt.Color(76, 184, 196));
        setColor1(new java.awt.Color(60, 211, 173));
        setRound(20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnValue, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnCarStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnCarStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.qt.view.component.imp.CarStatusPanal pnCarStatus;
    private com.qt.view.component.imp.InfoPanel pnInfo;
    private com.qt.view.component.imp.ValuePanal pnValue;
    // End of variables declaration//GEN-END:variables

    JLabel getImageLabel() {
        return this.pnInfo.getImageLabel();
    }
}
